### ISSUE TITLE
Provide deeponion AppImage on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [deeponion/deeponion-legacy#67]
Please provide a deeponion AppImage for download on https://github.com/deeponion/deeponion/releases. Thanks.

**Comment by brakmic** [comment]
Please do not misuse the Issues sections for personal wishes, or your risk of being blocked & reported to GitHub admins.
 
This section is for *errors & problems with current versions only*. 

I have already explained to you that we don't have enough manpower to fulfill all of your wishes.
This is sad, but that's life when you use Open Source software.

We do not owe you or anyone else anything. If we provide something then this doesn't mean that you or anyone else has any reason or right to expect more. 

And because I have already answered the same question all subsequent questions simply drain our limited time. This is not in the best interest of the DeepOnion community.

Remember, you are not paying us and we are working on this project for free!

Welcome to Open Source!
